### ISSUE TITLE
[FEATURE] Implement `RollingTextFileLogAdapter`

### ISSUE THREAD

**Issue by guibranco** [guibranco/CrispyWaffle#37]
**Is your feature request related to a problem? Please describe.**
Implement the class [RollingTextFileLogAdapter](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Log/Adapters/RollingTextFileLogAdapter.cs)

**Describe the solution you'd like**
I would like to have an implementation of the Rolling Text File Log Adapter.
It should be a text file log adapter and should handle the file size/name.
A new file must be created whenever the file reaches the configured maximum size or the number of messages per file.

The rules are:
- file size (B, MB, GB, ...)
- quantity of messages (number of messages to roll up)

**Comment by Mohammad-Haris** [comment]
@guibranco I would be delighted to take this one too; though I might have some question along the way.

**Comment by guibranco** [comment]
Yes, sure! It has been assigned to you already. Let me know your questions...

**Comment by Mohammad-Haris** [comment]
@guibranco In the methods where the file name is explicitly specified, like in `Debug(string content, string fileName)`, we still have to apply the quantity of messages and file size check? Because if the max constraint is achieved the file name will be changed, e.g. a suffix might have to be added.
Also, the `fileName` is expected to be a complete path or just a file name?

**Comment by guibranco** [comment]
These `Debug` methods are for persisting specific content in a specific file. They don't apply to the scenario of this issue.

 So, to answer your question clearly, no, it does not apply, and you can reuse it as it is on your implementation without any change.
